services:
  postgres:
    image: postgres:17
    container_name: citi_bike_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citi_bike
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio:latest
    container_name: citi_bike_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"  # acessing the minio server
      - "9001:9001"  # acessing the minio console
    volumes:
      - minio_data:/data
    
  # --- Airflow Orchestration ---
  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on: [postgres-airflow]
    environment: &airflow-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email a@a.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./citibike_dbt:/opt/airflow/citibike_dbt

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on: [airflow-init]
    environment: *airflow-env
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./citibike_dbt:/opt/airflow/citibike_dbt
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on: [airflow-init]
    environment: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./citibike_dbt:/opt/airflow/citibike_dbt
    command: scheduler

volumes:
  postgres_data:
  minio_data:
  airflow-db: