version: 2
sources:
  - name: silver
    tables:
      - name: trips
        meta:
          external_location: >
            {% if target.name == 'ci' %}
              read_parquet('test_fixtures/sample_trips.parquet')
            {% else %}
              read_parquet('s3://silver/citibike/**/*.parquet', hive_partitioning=true)
            {% endif %}

# This YAML is basically giving a friendly name to your data in MinIO so dbt can refer to it easily.
# source = silver
# dataset = trips
# silver
#   │
#   └── trips
#         │
#         └── points to
#              ↓
#         s3://silver/citibike/**/*.parquet

